name: Salesforce Skynet

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  qa-check-only:
    if: github.event_name == 'pull_request' && !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    environment: QA
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SFDX
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
        mkdir sfdx-cli
        tar xJf sf-linux-x64.tar.xz -C sfdx-cli --strip-components 1
        echo "$PWD/sfdx-cli/bin" >> $GITHUB_PATH

    - name: Auth
      run: |
        openssl rsa -passin pass:${{secrets.SERVER_KEY_PASS}} -in ${{ vars.ENV_NAME }}/server.pass.key -out server.key
        sf org login jwt --username ${{secrets.USER_NAME}} --jwt-key-file server.key --alias qa-org --set-default --client-id ${{secrets.CLIENT_ID}}

    - name: Run check-only
      run: sf project deploy validate --source-dir force-app/main/default/

    - name: Logout
      run: sf org logout --all -p

