name: Salesforce Skynet

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, labeled]

jobs:
  check-only:
    if: github.event_name == 'pull_request' || github.event.action == 'labeled'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run check-only
      run: echo "Run check-only deployment script here"
      # Replace with your check-only deployment script/command

  deploy:
    if: github.event_name == 'pull_request' && github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'ready to merge')
    needs: check-only
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Salesforce
      run: echo "Run actual deployment script here"
      # Replace with your actual deployment script/command

    - name: Merge PR
      if: success()
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.MY_GITHUB_TOKEN}}
        script: |
          github.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number
          });
