name: Salesforce Skynet

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, labeled]
  push:
    branches:
      - main 
    tags:
      - 'uat'  
      - 'prod' 

jobs:
  qa-check-only:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: QA
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Run check-only
      run: echo "Deploy to QA using environment secrets for ${{ vars.ENV_NAME }} using ${{secrets.ENV_KEY}}"
      
  qa-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: QA
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Deploy
      run: echo "Deploy to QA using environment secrets for ${{ vars.ENV_NAME }} using ${{secrets.ENV_KEY}}"
     

    - name: Push UAT Tag
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        CUSTOM_TAG: uat
  

  uat-deploy:
    if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, 'uat')
    runs-on: ubuntu-latest
    environment: UAT
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Deploy to UAT
      run: echo "Deploy to UAT using environment secrets for ${{ vars.ENV_NAME }} using ${{secrets.ENV_KEY}}"

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        CUSTOM_TAG: prod

 


  prod-deploy:
    if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, 'prod')
    runs-on: ubuntu-latest
    environment: PROD
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to PROD
      run: echo "Deploy to PROD using environment secrets for ${{ vars.ENV_NAME }} using ${{secrets.ENV_KEY}}"

    - name: Push Tag
      if: success()
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        WITH_V: true
  

