name: Salesforce Skynet

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, labeled]
  push:
    branches:
      - main  # Se agrega para desencadenar despliegue en QA después de la fusión
    tags:
      - '*-uat'  
      - '*-prod' 

jobs:
  qa-check-only:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: QA
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run check-only
      run: echo "Deploy to QA using environment secrets for ${{ vars.ENV_NAME }} using ${{secrets.ENV_KEY}}"
      
  qa-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: QA
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy
      run: echo "Deploy to QA using environment secrets for ${{ vars.ENV_NAME }} using ${{secrets.ENV_KEY}}"

    
  
  uat-check-only:
    if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-uat')
    runs-on: ubuntu-latest
    environment: UAT
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to UAT
      run: echo "Deploy to UAT using environment secrets for ${{ vars.ENV_NAME }} using ${{secrets.ENV_KEY}}"

  uat-deploy:
    if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-uat')
    runs-on: ubuntu-latest
    environment: UAT
    needs: uat-check-only
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to UAT
      run: echo "Deploy to UAT using environment secrets for ${{ vars.ENV_NAME }} using ${{secrets.ENV_KEY}}"

  prod-check-only:
    if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-prod')
    runs-on: ubuntu-latest
    environment: PROD
    needs: uat-deploy
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to PROD
      run: echo "Deploy to PROD using environment secrets for ${{ vars.ENV_NAME }} using ${{secrets.ENV_KEY}}"


  prod-deploy:
    if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-prod')
    runs-on: ubuntu-latest
    environment: PROD
    needs: prod-check-only
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to PROD
      run: echo "Deploy to PROD using environment secrets for ${{ vars.ENV_NAME }} using ${{secrets.ENV_KEY}}"

