name: Salesforce Skynet

on:
  push:
    branches:
      - main 
env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:

  qa-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: QA
    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Deploy
      run: echo "Deploy to QA using environment secrets for ${{ vars.ENV_NAME }} using ${{secrets.ENV_KEY}}"
     
    - name: Delete QA Tag
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git config --global --add safe.directory /github/workspace
        if git rev-parse -q --verify "refs/tags/QA"; then
          git tag -d QA
          git push --delete origin QA
        fi

    - name: Create QA Tag
      uses: anothrNick/github-tag-action@1.64.0
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        CUSTOM_TAG: 'QA'

  create-version:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: qa-deploy
    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: 'main'
        persist-credentials: false
        
    - name: Run Semantic Release
      run: |
        npm -g install @semantic-release/git semantic-release && semantic-release
        npx semantic-release --branches main     

  uat-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: UAT
    needs: qa-deploy
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Deploy to UAT
      run: echo "Deploy to UAT using environment secrets for ${{ vars.ENV_NAME }} using ${{secrets.ENV_KEY}}"

    - name: Create UAT Tag
      run: |
        git config --global --add safe.directory /github/workspace
        if git rev-parse -q --verify "refs/tags/UAT"; then
          git tag -d UAT
          git push --delete origin UAT
        fi

    - name: Create UAT Tag
      uses: anothrNick/github-tag-action@1.64.0
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        CUSTOM_TAG: 'UAT'
  
  prod-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: PROD
    needs: uat-deploy
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to PROD
      run: echo "Deploy to PROD using environment secrets for ${{ vars.ENV_NAME }} using ${{secrets.ENV_KEY}}"


        

  

